### ISSUE TITLE
 pretrain_model isn't match the network structure,why?

### ISSUE THREAD

**Issue by GuangyanZhang** [DeepSceneSeg/AdapNet#2]
I had dowanload the pretrain_model,but I found pretrain_model isn't match the network structure,why?
is the link exchange?

**Comment by GuangyanZhang** [comment]
and can you give a link to download the exactly resnet_v1_50 tensorflow pre-trained model?thank you .

**Comment by avalada** [comment]
Please download the package again. It should work now.
